project:
  type: website

website:
  title: "My experience with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thiessen2003
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-thiessen/
format:
  html:
    theme: lumen
    css: styles.css

execute:
  freeze: auto


